// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RoseLibML.Transformer.Templates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ComposerTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"
 AddTemplateHeader(); 
            
            #line default
            #line hidden
            this.Write("\r\nusing Microsoft.CodeAnalysis.CSharp;\r\nusing Microsoft.CodeAnalysis.CSharp.Synta" +
                    "x;\r\nusing System;\r\nusing System.Linq;\r\n\r\nnamespace RoseLibApp.RoseLib.Composers\r" +
                    "\n{\r\n    public partial class ");
            
            #line 12 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composer));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public ");
            
            #line 14 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composer));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 14 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 14 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"

            for(int i = 0; i < methodParameters.Count; i++)
            {
                Write("string " + methodParameters[i]);
                if(i < methodParameters.Count-1){
                    Write(", ");
                }
            }
        
            
            #line default
            #line hidden
            this.Write(")  \r\n        {\r\n\r\n            if (!IsAtRoot())\r\n            {\r\n                th" +
                    "row new Exception(\"A ");
            
            #line 27 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composer.Replace("Composer", "").ToLower()));
            
            #line default
            #line hidden
            this.Write(" must be selected (which is also a root to the composer)\");\r\n            }\r\n\r\n   " +
                    "         string fragment = String.Format(\"");
            
            #line 30 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fragment));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 30 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"

            for(int i = 0; i < methodParameters.Count; i++)
            {
                Write(", " + methodParameters[i]);
            }
        
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            var compilationUnit = CSharpSyntaxTree.ParseText(fragment).GetR" +
                    "oot();\r\n\r\n            var members = (compilationUnit as CompilationUnitSyntax).M" +
                    "embers.ToArray();\r\n\r\n            var newNode = (CurrentNode as ");
            
            #line 41 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(node));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 41 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibML\Transformer\Templates\ComposerTemplate.tt"

                if (rootCSType.Equals("UsingDirective")) {
                    Write(".AddUsings");
                }
                else {
                    Write(".AddMembers");
                }
                
            
            #line default
            #line hidden
            this.Write("(members);\r\n            \r\n            Replace(CurrentNode, newNode, null);\r\n\r\n   " +
                    "         return this;\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
