// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RoseLibLS.Transformer.Templates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class MethodComposerTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"
 AddTemplateHeader(); 
            
            #line default
            #line hidden
            this.Write("\r\nusing Microsoft.CodeAnalysis.CSharp;\r\nusing Microsoft.CodeAnalysis.CSharp.Synta" +
                    "x;\r\nusing System;\r\n\r\nnamespace RoseLibApp.RoseLib.Composers\r\n{\r\n    public parti" +
                    "al class ");
            
            #line 11 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composer));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public ");
            
            #line 13 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composer));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 13 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 13 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"

            for(int i = 0; i < methodParameters.Count; i++)
            {
                Write("string " + methodParameters[i]);
                if(i < methodParameters.Count-1){
                    Write(", ");
                }
            }
        
            
            #line default
            #line hidden
            this.Write(")  \r\n        {\r\n            if (!IsAtRoot())\r\n            {\r\n                thro" +
                    "w new Exception(\"A ");
            
            #line 25 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composer.Replace("Composer", "").ToLower()));
            
            #line default
            #line hidden
            this.Write(" must be selected (which is also a root to the composer)\");\r\n            }\r\n\r\n   " +
                    "         string fragment = string.Format(\"");
            
            #line 28 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fragment));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 28 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"

            for(int i = 0; i < methodParameters.Count; i++)
            {
                Write(", " + methodParameters[i]);
            }
            
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            var statement = SyntaxFactory.ParseStatement(fragment);\r\n\r\n    " +
                    "        var newNode = (CurrentNode as ");
            
            #line 37 "C:\Users\Marijana Kolosnjaji\Documents\Faks\Master studije\Master\RoseLibML\RoseLibLS\Transformer\Templates\MethodComposerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(composer.Replace("Composer", "")));
            
            #line default
            #line hidden
            this.Write("DeclarationSyntax).AddBodyStatements(statement);\r\n\r\n            Replace(CurrentNo" +
                    "de, newNode, null);\r\n\r\n            return this;\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
